### ISSUE TITLE
Manuskript 0.5.0: a checklist

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#182]
Manuskript 0.5.0 is out ! 
**Thanks to everyone for the work put into it.** I'm amazed to see the small community gathering here and working together. Every contribution deeply touches me. I really hope our software will help many writers to create and produce awesome work!

A few things still need to be done for the 0.5.0 release. Not sure this is the proper place to post that memo, but in case... Here is checklist of things to do:

## Must do

- [x] [Create pyInstaller packages](https://github.com/olivierkes/manuskript/wiki#packaging-for-release-zip-file) for: 
    - [x] Windows
    - [x] Mac
    - [x] GNU/Linux (32/64)
- [x] Update the [release](https://github.com/olivierkes/manuskript/releases/tag/0.5.0) on github (adding packages to download, maybe a small description and/or changelog)
- [x] Update [README.md](https://github.com/olivierkes/manuskript/blob/master/README.md) here on github
    - [x] Point to the wiki for more accurate procedures
    - [x] New up to date screenshot
- [x] Update the [download page](http://www.theologeek.ch/manuskript/download) on the website
- [x] Write a release post for [the website](http://www.theologeek.ch/manuskript), listing new stuff (see the [CHANGELOG.md](https://github.com/olivierkes/manuskript/blob/master/CHANGELOG.md))

## Possibly

- [ ] Write ["feature" articles](http://www.theologeek.ch/manuskript/category/features/) on the website describing some of the new features
- [ ] [Translate manuskript](https://github.com/olivierkes/manuskript/wiki/Translate-Manuskript) in new languages
- [ ] Write documentation and [tutorials](http://gedakc.users.sourceforge.net/display-doc.php?name=manuskript-novel-writing)

But for now... I need some sleep :)
Cheers !

**Comment by vithiri** [comment]
Congratulations on what looks to be a very strong release! Just in time for NaNoWrimo as well (for those brave enough to participate over there). :+1: :tada:

**Comment by gedakc** [comment]
The following two manuskript PyInstaller packages have been uploaded to [Github Manuskript Release 0.5.0](https://github.com/olivierkes/manuskript/releases/tag/0.5.0), and [SourceForge Manuskript 0.5.0](https://sourceforge.net/projects/manuskript/files/manuskript/manuskript-0.5.0/):

* `manuskript-0.5.0-linux64.zip`
* `win32.zip`

**Comment by vithiri** [comment]
@gedakc I noticed that Windows 10 potentially did a better job of blocking 0.5.0 from running compared to 0.4.0. I had to click More and approve the running of the software due to the publisher being unknown, which I at least don't believe I had to do with 0.4.0 yesterday when I checked it.

I could be mistaken though, I'm not very used to running Windows software. 😄

**Comment by gedakc** [comment]
> I had to click More and approve the running of the software due to the publisher being unknown

If I recall correctly I only had to give permission for the executable to run once.  Windows 10 seems to remember my response.

**Comment by gedakc** [comment]
@olivierkes are you going to announce the 0.5.0 release on your Manuskript Wordpress site?

**Comment by olivierkes** [comment]
@gedakc I'm quite busy now, is this something you could do?
Otherwise I'll try to find the time.

**Comment by gedakc** [comment]
Sure, I'll can make the announcement.  I just noticed that a draft post was already created and I didn't want to step on your toes.  ;-)

**Comment by gedakc** [comment]
I have updated the download page and created a new release post on the web site.

**Comment by olivierkes** [comment]
Thanks !!

**Comment by gedakc** [comment]
FYI:  I tried creating a linux32 PyInstaller package on 32-bit Debian 8 Jessie.  While I was able to successfully create a `manuskript-0.5.0-linux32.zip` PyInstaller package, the package would not run on the two other distros I tried:  32-bit openSUSE 42_1, and 32-bit xubuntu 14.04.  The error messages were different and I was unable to determine workarounds.

For now I think it best for users of 32-bit Linux distros to [Run Manuskript from Source Code on Linux](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Linux).

**Comment by gedakc** [comment]
Thanks to @katafrakt creating a Mac OS X PyIntaller package, we now have packages for three OSes.  I have uploaded the package to our official release locations and also updated the [web site download page](http://www.theologeek.ch/manuskript/download/).

**Comment by gedakc** [comment]
Recently I created PR #205 to update the README.md file to reflect the Manuskript 0.5.0 release.

**Comment by gedakc** [comment]
Closing this issue because we've already moved on and released 0.6.0.

**Comment by gedakc** [comment]
Marking this as **invalid** to prevent it from being automatically included in the CHANGELOG.
