### ISSUE TITLE
Manuskript 0.10.0 release check list

### ISSUE THREAD

**Issue by gedakc** [olivierkes/manuskript#657]
Following is a check list of tasks for the Manuskript 0.10.0 release:

This check list is based on the [Steps To Create An Official Manuskript Release](https://github.com/olivierkes/manuskript/wiki/Steps-To-Create-An-Official-Manuskript-Release)

## Todo

- [x] Decide which issues and pull requests are to be included in [0.10.0 milestone](https://github.com/olivierkes/manuskript/milestone/9).
- [x] Finish develop/test/review/merge for [0.10.0 milestone](https://github.com/olivierkes/manuskript/milestone/9)
- [x] Create release area and cleanup milestones for issues and pull requests
- Notify translators of upcoming release (_I still don't know how to do this_)
- [x] Incorporate translation updates
- [x] Prepare changelog
- [x] Prepare source code for production release
- [x] Add development changes to master branch for official release
- [x] [Create release packages](https://github.com/olivierkes/manuskript/wiki#packaging-for-release-package-file) for:
    - [x] GNU/Linux
    - [x] Mac OS X
    - [x] Windows
- [x] Upload release packages
- [ ] Update project web site
    - [x] Update [Download](http://www.theologeek.ch/manuskript/download) on the website
    - [x] Write a release post for [the website](http://www.theologeek.ch/manuskript)

Please feel free to comment if I've overlooked something important, or you see an opportunity to improve the process.

**Comment by gedakc** [comment]
Removed milestone **0.10.** from left hand side.  Otherwise it hampers going through the release steps as written because this issue will not be closed until after the entire official release has been completed.

**Comment by gedakc** [comment]
Manuskript 0.10.0 was released on September 30, 2019.

**Comment by worstje** [comment]
Thank you for your hard work. I didn't have much knowledge of any of those steps which led me to be silent, so I kind of remained silent.. but I am very grateful for the time and effort this has taken. 👍
