### ISSUE TITLE
Manuskript 0.11.0 release check list

### ISSUE THREAD

**Issue by gedakc** [olivierkes/manuskript#716]
The reason for this release is to get a critical bug fix released that prevents loss of data when copying and pasting into the **Notes / References** and **Summary** sections.  No other new functionality is planned.

Following is a check list of tasks for the Manuskript 0.11.0 release:

This check list is based on the [Steps To Create An Official Manuskript Release](https://github.com/olivierkes/manuskript/wiki/Steps-To-Create-An-Official-Manuskript-Release)

## Todo

- [x] Decide which issues and pull requests are to be included in [0.11.0 milestone](https://github.com/olivierkes/manuskript/milestone/10).
- [x] Finish develop/test/review/merge for [0.11.0 milestone](https://github.com/olivierkes/manuskript/milestone/10)
- [x] Create release area and cleanup milestones for issues and pull requests
- Notify translators of upcoming release (_I still don't know how to do this_)
- [x] Incorporate translation updates
- [x] Prepare changelog
- [x] Prepare source code for production release
- [x] Add development changes to master branch for official release
- [x] [Create release packages](https://github.com/olivierkes/manuskript/wiki#packaging-for-release-package-file) for:
    - [x] GNU/Linux
    - Mac OS X - **HELP NEEDED FROM MAC OS X USER(s).  See issue #696.**
    - [x] Windows
- [x] Upload release packages
- [x] Update project web site
    - [x] Update [Download](http://www.theologeek.ch/manuskript/download) on the website
    - [x] Write a release post for [the website](http://www.theologeek.ch/manuskript)

Please feel free to comment if I've overlooked something important, or you see an opportunity to improve the process.

**Comment by gedakc** [comment]
Manuskript 0.11.0 was released on January 18, 2020.
